#!/usr/bin/env bun
// Agent Mesh Gateway CLI - 交互式初始化向导
import { existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { logger } from '../core/logger.js';

const CONFIG_DIR = join(Bun.env.HOME || '~', '.config', 'agentmesh');
const _metaDir = (import.meta as any).dir || (import.meta as any).dirname || '.';
const PROJECT_ROOT = dirname(dirname(_metaDir));

function prompt(msg: string, def?: string): string {
  const suffix = def ? ` [${def}]` : '';
  process.stdout.write(`  ${msg}${suffix}: `);
  const input = _readLine()?.trim();
  return input || def || '';
}

function _readLine(): string | undefined {
  // 同步读取 fallback（异步版本用 readLineAsync）
  return undefined;
}

async function readLineAsync(): Promise<string> {
  const decoder = new TextDecoder();
  for await (const chunk of Bun.stdin.stream() as any) {
    const text = typeof chunk === 'string' ? chunk : decoder.decode(chunk as Uint8Array);
    return text.trim();
  }
  return '';
}

async function promptAsync(msg: string, def?: string): Promise<string> {
  const suffix = def ? ` [${def}]` : '';
  process.stdout.write(`  ${msg}${suffix}: `);
  const input = await readLineAsync();
  return input.trim() || def || '';
}

async function promptYesNoAsync(msg: string): Promise<boolean> {
  const ans = (await promptAsync(`${msg} (y/n)`, 'y')).toLowerCase();
  return ans === 'y' || ans === 'yes';
}

export async function runSetup() {
  console.log(`
╔═══════════════════════════════════════════════════╗
║     Agent Mesh Gateway - Setup                   ║
╚═══════════════════════════════════════════════════╝
`);
  console.log('This wizard will help you configure the gateway.\n');

  // 1. API Keys
  console.log('── API Keys ──');
  const deepseekKey = await promptAsync('DeepSeek API Key', Bun.env.DEEPSEEK_API_KEY);
  const openaiKey = await promptAsync('OpenAI API Key', Bun.env.OPENAI_API_KEY);
  const openrouterKey = await promptAsync('OpenRouter API Key', Bun.env.OPENROUTER_API_KEY);

  // 2. Port
  console.log('\n── Server ──');
  const port = parseInt(await promptAsync('Port', '3000'), 10);
  const logLevel = await promptAsync('Log level (debug/info/warn/error)', 'info');

  // 3. Write .env
  const envContent = `# Agent Mesh Gateway - Generated by setup
DEEPSEEK_API_KEY=${deepseekKey}
OPENAI_API_KEY=${openaiKey}
OPENROUTER_API_KEY=${openrouterKey}
LOG_LEVEL=${logLevel}
PORT=${port}
`;
  const envPath = join(PROJECT_ROOT, '.env');
  writeFileSync(envPath, envContent);
  console.log(`  ✅ .env written to ${envPath}`);

  // 4. Config dir
  if (!existsSync(CONFIG_DIR)) {
    Bun.spawnSync(['mkdir', '-p', CONFIG_DIR]);
  }
  console.log(`  ✅ Config directory: ${CONFIG_DIR}`);

  // 5. Check tools
  console.log('\n── Tool Checks ──');
  const checks: Array<[string, string[]]> = [
    ['bun', ['bun', '--version']],
    ['codexbar', ['codexbar', '--version']],
    ['docker', ['docker', '--version']],
    ['ollama', ['ollama', '--version']],
  ];
  for (const [name, cmd] of checks) {
    const proc = Bun.spawnSync({ cmd, stdout: 'pipe', stderr: 'pipe' });
    const status = proc.exitCode === 0 ? '✅' : '⚠️ (not required)';
    console.log(`  ${status} ${name}`);
  }

  console.log(`
╔═══════════════════════════════════════════════════╗
║     Setup Complete!                              ║
╠═══════════════════════════════════════════════════╣
║  Start:  bun run src/index.ts                    ║
║  Or:     ./start.sh                              ║
║  Help:   agentmesh help                          ║
╚═══════════════════════════════════════════════════╝
`);
}

// 直接运行
if (import.meta.main) {
  runSetup().catch(err => {
    logger.error(`Setup failed: ${err.message}`);
    process.exit(1);
  });
}
